### ISSUE TITLE
push module is using HGMO::get_json_pushes (should be HGMO::json_pushes)

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#62]
```
17:27:57.253 | WARNING  | mozci.task:54  - Bad group name in task V8wnfIiQSGmU-CRl45qmfA: /Users/cltbld/tasks/task_1581459369/build/tests/marionette/tests/testing/marionette/harness/marionette_harness/tests/unit-tests.ini
Traceback (most recent call last):
  File "testmozci.py", line 6, in <module>
    print(p.get_regressions("label"))
  File "c:\mozilla-build\python3\lib\site-packages\adr\util\memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "c:\Users\elvis\mozci\mozci\push.py", line 449, in get_regressions
    for name, child_count in self.get_candidate_regressions(runnable_type).items():
  File "c:\mozilla-build\python3\lib\site-packages\adr\util\memoize.py", line 26, in method_call
    cache[args] = self.func(instance, *args)
  File "c:\Users\elvis\mozci\mozci\push.py", line 427, in get_candidate_regressions
    other = other.child
  File "c:\mozilla-build\python3\lib\site-packages\adr\util\memoize.py", line 44, in __get__
    setattr(instance, name, self.func(instance))
  File "c:\Users\elvis\mozci\mozci\push.py", line 125, in child
    return self.create_push(self.id + 1)
  File "c:\Users\elvis\mozci\mozci\push.py", line 97, in create_push
    result = self._hgmo.get_json_pushes(
AttributeError: 'HGMO' object has no attribute 'get_json_pushes'
```

This is a regression from #59. The method is actually called `json_pushes`, not `get_json_pushes`.
