### ISSUE TITLE
Fix usage of old confidence_medium 

### ISSUE THREAD

**Issue by La0** [mozilla/mozci#633]
A bug has been introduced in https://github.com/mozilla/mozci/pull/632 that breaks classification tasks withe error message

```
Couldn't classify push autoland/ca668bf5c75eacd1fc8691149090b3eda4a3b924: classify() got an unexpected keyword argument 'confidence_medium'.
```

Example task https://community-tc.services.mozilla.com/tasks/RzsuTufRTKmrBk9WnrTH7w/runs/0/logs/public/logs/live.log
