### PR TITLE
Fix confidence attributes renaming

### LINKED ISSUE #633: Fix usage of old confidence_medium
A bug has been introduced in https://github.com/mozilla/mozci/pull/632 that breaks classification tasks withe error message

```
Couldn't classify push autoland/ca668bf5c75eacd1fc8691149090b3eda4a3b924: classify() got an unexpected keyword argument 'confidence_medium'.
```

Example task https://community-tc.services.mozilla.com/tasks/RzsuTufRTKmrBk9WnrTH7w/runs/0/logs/public/logs/live.log

### PR DESCRIPTION
**Pull request by EvaBardou**
Closes #633

### CODE REVIEW

**Comment by EvaBardou** [comment]
> LGTM! Bonus points if you add type definitions to `handle` (basically just `def handle(self) -> None`) so mypy will catch these kinds of errors from now on.

@marco-c Isn't it already done?
See:
```
def classify(
        self,
        intermittent_confidence_threshold: float = 0.8,
        real_confidence_threshold: float = 0.9,
    ) -> Tuple[PushStatus, Regressions]:
```

**Comment by marco-c** [comment]
`classify` has type definitions, but `handle` doesn't, so mypy doesn't check `handle`.

**Review by La0 — APPROVED** [review]
Classification works again locally :+1:
