### PR TITLE
Extend the classify command to perform backfills and retriggers

### LINKED ISSUE #654: Extend the classify command to perform backfills (and choose between retriggers or backfills) when it needs more information
The algorithm behind the classify command isn't always able to give a decision between "good" or "bad" and sometimes needs more information in order to be sure.

When a situation like this happens and the classify command returns "unknown", it should automatically identify and perform the set of actions (retriggers and/or backfills) that would be necessary to gather enough information.

#619 implemented support for retriggers, but retriggers might not always be the best action. See https://github.com/mozilla/mozci/pull/619#issuecomment-1033590959.

Depends on https://github.com/mozilla/mozci/issues/504 and https://github.com/mozilla/mozci/issues/508 and https://github.com/mozilla/mozci/issues/743.

### PR DESCRIPTION
**Pull request by EvaBardou**
Closes #654 

@marco-c Please do not hesitate to let me know if there is anything I have misunderstood from the steps you specified in the issue.

### CODE REVIEW

File: mozci/console/commands/push.py [hunk 1]
```diff
@@ -225,12 +226,54 @@ def handle(self) -> None:
...
+
+                def retrigger_failures(groups, count):
+                    groups_with_failures = {
+                        name: failing_tasks
+                        for name, failing_tasks in groups.items()
+                        if failing_tasks
+                    }
+                    if not groups_with_failures:
+                        return
+
```
Comment (marco-c) [inline mozci/console/commands/push.py:251]: Could you assert here that all failing tasks did fail?

File: mozci/console/commands/push.py [hunk 2]
```diff
@@ -225,12 +226,54 @@ def handle(self) -> None:
...
 
+        try:
+            backfill_limit = int(self.option("backfill-limit"))
+        except ValueError:
+            raise Exception("Provided --backfill-limit should be an int.")
+
         for push in pushes:
             try:
-                classification, regressions = push.classify(**classify_parameters)
+                classification, regressions, to_retrigger_or_backfill = push.classify(
```
Comment (marco-c) [inline mozci/console/commands/push.py:236]: There is a problem to solve: if we run the script and retrigger something, we don't want to retrigger again on the next run if the previously retriggered tasks haven't finished yet.
We should make sure not to retrigger if there is any task in progress that is running the same groups (similar logic as #697).

File: mozci/push.py [hunk 3]
```diff
@@ -1207,12 +1223,35 @@ def _map_failing_tasks(groups):
             # Link all the failing tasks on the given groups
             return {name: self.group_summaries[name].failing_tasks for name in groups}
 
+        real_failures_to_be_retriggered = (groups_regressions & groups_high).difference(
```
Comment (marco-c) [inline mozci/push.py:1226]: Can you add comments explaining how we decide the groups to retrigger and backfill?
You can simply copy & paste my comments from the issue and reword them if necessary

**Comment by marco-c** [comment]
We should add a config option to filter task names that we are allowed to retrigger/backfill (e.g. we might only want to retrigger/backfill "*-linux-*" tasks).

File: mozci/push.py (hunk 3 above)
Comment (EvaBardou) [reply mozci/push.py:1226]: I was writing the comments and wondered if it would be enough to link [your comment](https://github.com/mozilla/mozci/issues/654#issuecomment-1139488070) directly in the code to avoid repeating everything?

File: mozci/console/commands/push.py (hunk 2 above)
Comment (marco-c) [reply mozci/console/commands/push.py:236]: Yeah, let's do #697 first.

File: mozci/console/commands/push.py (hunk 1 above)
Comment (marco-c) [reply mozci/console/commands/push.py:251]: Not really necessary at the moment, but better to be defensive to potential future changes given that retriggers and backfills can be very expensive.

File: mozci/push.py (hunk 3 above)
Comment (marco-c) [reply mozci/push.py:1226]: Sounds good!

**Comment by marco-c** [comment]
> > We should add a config option to filter task names that we are allowed to retrigger/backfill (e.g. we might only want to retrigger/backfill "_-linux-_" tasks).
> 
> @marco-c so we could imagine having a new parameter in the config called `retriggerable-backfillable-task-names` storing a list of patterns that we allow to retrigger/backfill like what we did for `autoclassification["test-suite-names"]`? If the parameter is empty do we allow to retrigger/backfill everything? Or nothing?

Sounds good. If the parameter is "*" we allow retriggering/backfilling everything, if the parameter is empty we allow nothing (so we have a way to totally disable it).

File: mozci/console/commands/push.py (hunk 2 above)
Comment (marco-c) [reply mozci/console/commands/push.py:236]: Or better, let's implement `is_group_running` first, we don't have to fix the full #697.

Comment (EvaBardou) [reply mozci/console/commands/push.py:236]: Will work on it early next week hopefully. :crossed_fingers:

File: mozci/console/commands/push.py [hunk 4]
```diff
@@ -787,8 +877,8 @@ def handle(self) -> None:
                     )
 
             if push.backedout or push.bustage_fixed_by:
-                group_classifications: dict[
-                    str, dict[tuple[str, str], set[str]]
+                group_classifications: Dict[
+                    str, Dict[Tuple[str, str], Set[str]]
```
Comment (marco-c) [inline mozci/console/commands/push.py:881]: Nit: why did you move to typing instead of built-in names?

File: mozci/console/commands/push.py [hunk 5]
```diff
@@ -314,6 +335,75 @@ def _serialize_regressions(regressions):
...
+            allowed_patterns,
+        )
+
+        # Backfill some failures
+        groups_to_backfill = {
+            name: failing_tasks
+            for name, failing_tasks in to_retrigger_or_backfill.backfill.items()
+            if failing_tasks
+        }
+        for index, (_, failing_tasks) in enumerate(groups_to_backfill.items()):
```
[the remark this answers is not in the document]
Comment (marco-c) [reply mozci/console/commands/push.py:397]: Or something like this should work too, so you don't have to manually implement the limit:
```Python
for failing_tasks in itertools.islice(groups_to_backfill.values(), backfill_limit):
```

File: mozci/console/commands/push.py [hunk 6]
```diff
@@ -314,6 +335,75 @@ def _serialize_regressions(regressions):
...
+    def retrigger_failures(self, groups, count, allowed_patterns):
+        groups_with_failures = {
+            name: failing_tasks
+            for name, failing_tasks in groups.items()
+            if failing_tasks
+        }
+        if not groups_with_failures:
+            return
+
+        # If there is more than one group with failing tasks, we should retrigger only one of them
```
Comment (marco-c) [inline mozci/console/commands/push.py:347]: Sorry I realize this wasn't clear in https://github.com/mozilla/mozci/issues/654#issuecomment-1145889375.
We should retrigger all groups, and if there is more than one task for a given group we should retrigger only one of the tasks.

File: mozci/console/commands/push.py [hunk 7]
```diff
@@ -207,6 +209,7 @@ class ClassifyCommand(Command):
         {--show-intermittents : If set, print tasks that should be marked as intermittent.}
         {--environment=testing : Environment in which the analysis is running (testing, production, ...)}
         {--retrigger-unknown : If set, retrigger UNKNOWN regressions}
+        {--backfill-limit=3 : Number of failing groups (missing information) to be backfilled.}
```
Comment (marco-c) [inline mozci/console/commands/push.py:212]: Let's also add a --retrigger-limit.

File: mozci/console/commands/push.py (hunk 4 above)
Comment (EvaBardou) [reply mozci/console/commands/push.py:881]: Linting was failing:
```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

mozci/console/commands/push.py:880: error: "dict" is not subscriptable, use "typing.Dict" instead
mozci/console/commands/push.py:880: error: "tuple" is not subscriptable, use "typing.Tuple" instead
mozci/console/commands/push.py:880: error: "set" is not subscriptable, use "typing.Set" instead
Found 3 errors in 1 file (checked 39 source files)
```

The change was introduced by https://github.com/mozilla/mozci/pull/781 and merged with a failing pipeline

Comment (marco-c) [reply mozci/console/commands/push.py:881]: Oh no, I did notice, it was fixed in #784.

Comment (EvaBardou) [reply mozci/console/commands/push.py:881]: So it might be because I'm using python 3.8, do you want me to revert the change?

Comment (EvaBardou) [reply mozci/console/commands/push.py:881]: Python 3.10 doesn't like me ahah:
> The virtual environment found in /home/eva/.cache/pypoetry/virtualenvs/mozci-BCG4KwUI-py3.10 seems to be broken.

Also you are using typing everywhere in mozci not built-in names

Comment (marco-c) [reply mozci/console/commands/push.py:881]: Yeah we were using typing because the feature to use built-in names was not available yet, but it is the future

File: mozci/console/commands/push.py [hunk 8]
```diff
@@ -314,6 +339,76 @@ def _serialize_regressions(regressions):
...
+            if failing_tasks
+        }
+        for failing_tasks in itertools.islice(
+            groups_to_backfill.values(), 0, backfill_limit
+        ):
+            for t in failing_tasks:
+                if t.label and any(
+                    fnmatch.fnmatch(t.label, pattern) for pattern in allowed_patterns
+                ):
+                    t.backfill(push)
```
Comment (marco-c) [inline mozci/console/commands/push.py:410]: @Archaeopteryx should we notify the group on Matrix when we trigger a backfill?

Comment (Archaeopteryx) [reply mozci/console/commands/push.py:410]: No, failures in the backfills is what is important.
